# Generated by Django 3.1.4 on 2020-12-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_delete_pokemonentity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplatePokemonEntity',
            new_name='PokemonEntity',
        ),
    ]
